export const GET_ERRORS = 'GET_ERRORS';
export const SET_CURRENT_USER = 'SET_CURRENT_USER';
export const TOGGLE_NAVBAR = 'TOGGLE_NAVBAR';
export const GET_ALL_WORKS = 'GET_ALL_WORKS';
export const GET_WORK_BY_ID = 'GET_WORK_BY_ID';
export const GET_ALL_CONTRACTS = 'GET_ALL_CONTRACTS';
export const GET_CONTRACT_BY_ID = 'GET_CONTRACT_BY_ID';
export const SEARCH_CONTRACTS = 'SEARCH_CONTRACTS';